export const GET_TOP_SIX_NEW_PRODUCTS = "product/GET_TOP_SIX_NEW_PRODUCTS";
export const GET_TOP_SIX_NEW_PRODUCTS_SUCCESS =
  "product/GET_TOP_SIX_NEW_PRODUCTS_SUCCESS";
export const GET_TOP_SIX_SELLING_PRODUCTS =
  "product/GET_TOP_SIX_SELLING_PRODUCTS";
export const GET_TOP_SIX_SELLING_PRODUCTS_SUCCESS =
  "product/GET_TOP_SIX_SELLING_PRODUCTS_SUCCESS";
export const GET_TOP_SIX_PRODUCTS_PROMOTION =
  "product/GET_TOP_SIX_PRODUCTS_PROMOTION";
export const GET_TOP_SIX_PRODUCTS_PROMOTION_SUCCESS =
  "product/GET_TOP_SIX_PRODUCTS_PROMOTION_SUCCESS";
export const GET_LIST_PRODUCTS_CONTENT = "product/GET_LIST_PRODUCTS_CONTENT";
export const GET_LIST_PRODUCTS_CONTENT_SUCCESS =
  "product/GET_LIST_PRODUCTS_CONTENT_SUCCESS";
